<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Name</name>
   <tag></tag>
   <elementGuidId>1ed90842-0925-4aa1-8ede-aed4e34c9d71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='userName-wrapper']/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;userName-wrapper&quot;)/div[@class=&quot;col-md-4 col-sm-6&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-4.col-sm-6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>762149b2-05ae-46e3-9c64-eb6adf8aaf92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-4 col-sm-6</value>
      <webElementGuid>d77596ff-f4a4-405d-928f-d395e0425ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userName-wrapper&quot;)/div[@class=&quot;col-md-4 col-sm-6&quot;]</value>
      <webElementGuid>c38b5197-a31e-48e8-a5f8-7c0d6e80589e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userName-wrapper']/div[2]</value>
      <webElementGuid>d85e7505-c15e-4e1b-bd98-002f149b78db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::div[1]</value>
      <webElementGuid>d8881947-06cc-4d1b-8d60-0d034d1834c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student Registration Form'])[1]/following::div[3]</value>
      <webElementGuid>e9448afc-664d-4e2d-8b50-3b1124a63c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::div[3]</value>
      <webElementGuid>6181f7e3-650d-414e-8d95-18e26c8d1788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/preceding::div[6]</value>
      <webElementGuid>dcf33729-ef2f-49ab-8cca-f75fb4683d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]</value>
      <webElementGuid>8a4ebed8-a4fc-40bd-a116-e5bc735ca566</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
