<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hobbies_Reading</name>
   <tag></tag>
   <elementGuidId>7622db97-88a0-45f0-9c14-2290430bf979</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hobbies-checkbox-2']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;hobbies-checkbox-2&quot;)[count(. | //*[@id = 'hobbies-checkbox-2']) = count(//*[@id = 'hobbies-checkbox-2'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hobbiesWrapper .col-md-9.col-sm-12 .custom-control.custom-checkbox.custom-control-inline input#hobbies-checkbox-2.custom-control-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e307ff1b-86db-40f4-b152-323eb1770093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>765a0f5b-06c8-4a26-baec-b718b6ff0e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hobbies-checkbox-2</value>
      <webElementGuid>0c505410-1ae6-4154-8feb-8507c6a0699f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hobbies-checkbox-2&quot;)</value>
      <webElementGuid>56e4ef17-3333-4f40-8dcc-d7a272a72051</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hobbies-checkbox-2']</value>
      <webElementGuid>31bea899-b8d0-49cd-a3ee-4a5a119fa625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'hobbies-checkbox-2']</value>
      <webElementGuid>9931aa10-af95-49bc-af3c-1301779f1a9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
