<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gender_Other</name>
   <tag></tag>
   <elementGuidId>33ebfca9-25fe-45b5-9e0a-f938af6ee129</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gender-radio-3']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'radio' and @id = 'gender-radio-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#genterWrapper .col-md-9.col-sm-12 .custom-control.custom-radio.custom-control-inline input#gender-radio-3.custom-control-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b6b6b050-10fb-487f-ac3b-fef963753509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gender-radio-3</value>
      <webElementGuid>bd63f4ad-ffd5-43da-8413-a45d9262309d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gender-radio-3&quot;)</value>
      <webElementGuid>4d514054-b4aa-41f8-8050-b48301f84b42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gender-radio-3']</value>
      <webElementGuid>02304825-9649-47d6-a48b-0702bb4bd15a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'gender-radio-3']</value>
      <webElementGuid>60b4c7d5-a58a-4152-81b8-2121f0ff0ac7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
