<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select_City</name>
   <tag></tag>
   <elementGuidId>90ae957a-77ec-4640-9159-b7dd25d32489</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @id = 'react-select-4-input']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;react-select-4-input&quot;)[count(. | //*[@id = 'react-select-4-input']) = count(//*[@id = 'react-select-4-input'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-4-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2cd5fba-09cc-4b02-8221-519cea6ae30d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eebda582-7968-4b8d-b6fe-c8d20f329d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-4-input</value>
      <webElementGuid>f85cef7a-066f-4eef-b1e4-0b2c53a04992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-4-input&quot;)</value>
      <webElementGuid>00b0958e-1f91-4f3d-ba1e-3f025ece998f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='react-select-4-input']</value>
      <webElementGuid>cd8debd1-56be-4c5f-956f-16f61a15bd9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'react-select-4-input']</value>
      <webElementGuid>8856c9e8-3bf3-4fe7-a402-da5dce84ddde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
