<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gender_Female</name>
   <tag></tag>
   <elementGuidId>80c11fb7-a8fa-4c8f-b184-0474c033fe55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gender-radio-2']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'radio' and @id = 'gender-radio-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#genterWrapper .col-md-9.col-sm-12 .custom-control.custom-radio.custom-control-inline input#gender-radio-2.custom-control-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c52d0fc1-1a6a-4768-a5d2-f6a01f007ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gender-radio-2</value>
      <webElementGuid>f4988cfe-c42c-4365-acf9-23c1d3f5c1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gender-radio-2&quot;)</value>
      <webElementGuid>6b6a41c0-45c4-439c-9a3c-269ac9cf22be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gender-radio-2']</value>
      <webElementGuid>59e48e0f-0402-42cb-8dae-3df95e423638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'gender-radio-2']</value>
      <webElementGuid>0bf3e0a2-c357-4acf-ae0f-85e3be864d3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
